//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Example {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.IOC;
    using uFrame.Kernel;
    using uFrame.MVVM;
    using uFrame.Serialization;
    
    
    public class ViewExampleSceneBase : uFrame.Kernel.Scene {
        
        public override string DefaultKernelScene {
            get {
                return "ExampleKernelScene";
            }
        }
        
        public virtual ViewExampleSceneSettings Settings {
            get {
                return _SettingsObject as ViewExampleSceneSettings;
            }
            set {
                _SettingsObject = value;
            }
        }
    }
    
    public class ViewExampleSceneLoaderBase : SceneLoader<ViewExampleScene> {
        
        protected override IEnumerator LoadScene(ViewExampleScene scene, Action<float, string> progressDelegate) {
            yield break;
        }
        
        protected override IEnumerator UnloadScene(ViewExampleScene scene, Action<float, string> progressDelegate) {
            yield break;
        }
    }
}
