//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Example {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.IOC;
    using uFrame.Kernel;
    using uFrame.MVVM;
    
    
    public class PlayerInfoLoaderBase : uFrame.Kernel.SystemLoader {
        
        private UIPlayerInfoController _UIPlayerInfoController;
        
        [uFrame.IOC.InjectAttribute()]
        public virtual UIPlayerInfoController UIPlayerInfoController {
            get {
                if (_UIPlayerInfoController==null) {
                    _UIPlayerInfoController = Container.CreateInstance(typeof(UIPlayerInfoController)) as UIPlayerInfoController;;
                }
                return _UIPlayerInfoController;
            }
            set {
                _UIPlayerInfoController = value;
            }
        }
        
        public override void Load() {
            Container.RegisterViewModelManager<UIPlayerInfoViewModel>(new ViewModelManager<UIPlayerInfoViewModel>());
            Container.RegisterController<UIPlayerInfoController>(UIPlayerInfoController);
        }
    }
}
