//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Example {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.IOC;
    using uFrame.Kernel;
    using uFrame.MVVM;
    using uFrame.MVVM.Bindings;
    using uFrame.Serialization;
    using UnityEngine;
    using UniRx;
    
    
    public partial class UIPlayerInfoViewModelBase : uFrame.MVVM.ViewModel {
        
        private P<String> _TitleProperty;
        
        private P<String> _UsernameProperty;
        
        private Signal<OnButtonClickedCommand> _OnButtonClicked;
        
        public UIPlayerInfoViewModelBase(uFrame.Kernel.IEventAggregator aggregator) : 
                base(aggregator) {
        }
        
        public virtual P<String> TitleProperty {
            get {
                return _TitleProperty;
            }
            set {
                _TitleProperty = value;
            }
        }
        
        public virtual P<String> UsernameProperty {
            get {
                return _UsernameProperty;
            }
            set {
                _UsernameProperty = value;
            }
        }
        
        public virtual String Title {
            get {
                return TitleProperty.Value;
            }
            set {
                TitleProperty.Value = value;
            }
        }
        
        public virtual String Username {
            get {
                return UsernameProperty.Value;
            }
            set {
                UsernameProperty.Value = value;
            }
        }
        
        public virtual Signal<OnButtonClickedCommand> OnButtonClicked {
            get {
                return _OnButtonClicked;
            }
            set {
                _OnButtonClicked = value;
            }
        }
        
        public override void Bind() {
            base.Bind();
            this.OnButtonClicked = new Signal<OnButtonClickedCommand>(this);
            _TitleProperty = new P<String>(this, "Title");
            _UsernameProperty = new P<String>(this, "Username");
        }
        
        public virtual void ExecuteOnButtonClicked() {
            this.OnButtonClicked.OnNext(new OnButtonClickedCommand());
        }
        
        public override void Read(ISerializerStream stream) {
            base.Read(stream);
        }
        
        public override void Write(ISerializerStream stream) {
            base.Write(stream);
        }
        
        protected override void FillCommands(System.Collections.Generic.List<uFrame.MVVM.ViewModelCommandInfo> list) {
            base.FillCommands(list);
            list.Add(new ViewModelCommandInfo("OnButtonClicked", OnButtonClicked) { ParameterType = typeof(void) });
        }
        
        protected override void FillProperties(System.Collections.Generic.List<uFrame.MVVM.ViewModelPropertyInfo> list) {
            base.FillProperties(list);
            // PropertiesChildItem
            list.Add(new ViewModelPropertyInfo(_TitleProperty, false, false, false, false));
            // PropertiesChildItem
            list.Add(new ViewModelPropertyInfo(_UsernameProperty, false, false, false, false));
        }
    }
    
    public partial class UIPlayerInfoViewModel {
        
        public UIPlayerInfoViewModel(uFrame.Kernel.IEventAggregator aggregator) : 
                base(aggregator) {
        }
    }
}
