//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Example {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.IOC;
    using uFrame.Kernel;
    using uFrame.MVVM;
    using uFrame.Serialization;
    using UniRx;
    using Example;
    
    
    public class TodoListControllerBase : uFrame.MVVM.Controller {
        
        private uFrame.MVVM.IViewModelManager _TodoListViewModelManager;
        
        [uFrame.IOC.InjectAttribute("TodoList")]
        public uFrame.MVVM.IViewModelManager TodoListViewModelManager {
            get {
                return _TodoListViewModelManager;
            }
            set {
                _TodoListViewModelManager = value;
            }
        }
        
        public IEnumerable<TodoListViewModel> TodoListViewModels {
            get {
                return TodoListViewModelManager.OfType<TodoListViewModel>();
            }
        }
        
        public override void Setup() {
            base.Setup();
            // This is called when the controller is created
        }
        
        public override void Initialize(uFrame.MVVM.ViewModel viewModel) {
            base.Initialize(viewModel);
            // This is called when a viewmodel is created
            this.InitializeTodoList(((TodoListViewModel)(viewModel)));
        }
        
        public virtual TodoListViewModel CreateTodoList() {
            return ((TodoListViewModel)(this.Create(Guid.NewGuid().ToString())));
        }
        
        public override uFrame.MVVM.ViewModel CreateEmpty() {
            return new TodoListViewModel(this.EventAggregator);
        }
        
        public virtual void InitializeTodoList(TodoListViewModel viewModel) {
            // This is called when a TodoListViewModel is created
            viewModel.OnBtnAddClicked.Action = this.OnBtnAddClickedHandler;
            TodoListViewModelManager.Add(viewModel);
        }
        
        public override void DisposingViewModel(uFrame.MVVM.ViewModel viewModel) {
            base.DisposingViewModel(viewModel);
            TodoListViewModelManager.Remove(viewModel);
        }
        
        public virtual void OnBtnAddClicked(TodoListViewModel viewModel) {
        }
        
        public virtual void OnBtnAddClickedHandler(OnBtnAddClickedCommand command) {
            this.OnBtnAddClicked(command.Sender as TodoListViewModel);
        }
    }
}
