//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Example {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.Kernel;
    using uFrame.MVVM;
    using uFrame.MVVM.Bindings;
    using uFrame.Serialization;
    using Example;
    
    
    public class TodoItemBase : object {
        
        private String _Content;
        
        private Boolean _Finished;
        
        public String Content {
            get {
                return _Content;
            }
            set {
                _Content = value;
            }
        }
        
        public Boolean Finished {
            get {
                return _Finished;
            }
            set {
                _Finished = value;
            }
        }
    }
    
    public class PageTypeChangedCommandBase : object {
        
        private PageType _PageType;
        
        public PageType PageType {
            get {
                return _PageType;
            }
            set {
                _PageType = value;
            }
        }
    }
    
    public class ItemClickedChangeComandBase : object {
        
        private TodoItemViewModel _TodoItem;
        
        public TodoItemViewModel TodoItem {
            get {
                return _TodoItem;
            }
            set {
                _TodoItem = value;
            }
        }
    }
}
