//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Example {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.IOC;
    using uFrame.Kernel;
    using uFrame.MVVM;
    
    
    public class TodoListSysLoaderBase : uFrame.Kernel.SystemLoader {
        
        private TodoListController _TodoListController;
        
        [uFrame.IOC.InjectAttribute()]
        public virtual TodoListController TodoListController {
            get {
                if (_TodoListController==null) {
                    _TodoListController = Container.CreateInstance(typeof(TodoListController)) as TodoListController;;
                }
                return _TodoListController;
            }
            set {
                _TodoListController = value;
            }
        }
        
        public override void Load() {
            Container.RegisterViewModelManager<TodoListViewModel>(new ViewModelManager<TodoListViewModel>());
            Container.RegisterController<TodoListController>(TodoListController);
        }
    }
}
