//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Example {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.IOC;
    using uFrame.Kernel;
    using uFrame.MVVM;
    
    
    public class TodoListSysLoaderBase : uFrame.Kernel.SystemLoader {
        
        private TodoListController _TodoListController;
        
        private TodoItemController _TodoItemController;
        
        private TodoEditorController _TodoEditorController;
        
        private EventMaskController _EventMaskController;
        
        [uFrame.IOC.InjectAttribute()]
        public virtual TodoListController TodoListController {
            get {
                if (_TodoListController==null) {
                    _TodoListController = Container.CreateInstance(typeof(TodoListController)) as TodoListController;;
                }
                return _TodoListController;
            }
            set {
                _TodoListController = value;
            }
        }
        
        [uFrame.IOC.InjectAttribute()]
        public virtual TodoItemController TodoItemController {
            get {
                if (_TodoItemController==null) {
                    _TodoItemController = Container.CreateInstance(typeof(TodoItemController)) as TodoItemController;;
                }
                return _TodoItemController;
            }
            set {
                _TodoItemController = value;
            }
        }
        
        [uFrame.IOC.InjectAttribute()]
        public virtual TodoEditorController TodoEditorController {
            get {
                if (_TodoEditorController==null) {
                    _TodoEditorController = Container.CreateInstance(typeof(TodoEditorController)) as TodoEditorController;;
                }
                return _TodoEditorController;
            }
            set {
                _TodoEditorController = value;
            }
        }
        
        [uFrame.IOC.InjectAttribute()]
        public virtual EventMaskController EventMaskController {
            get {
                if (_EventMaskController==null) {
                    _EventMaskController = Container.CreateInstance(typeof(EventMaskController)) as EventMaskController;;
                }
                return _EventMaskController;
            }
            set {
                _EventMaskController = value;
            }
        }
        
        public override void Load() {
            Container.RegisterViewModelManager<TodoListViewModel>(new ViewModelManager<TodoListViewModel>());
            Container.RegisterController<TodoListController>(TodoListController);
            Container.RegisterViewModelManager<TodoItemViewModel>(new ViewModelManager<TodoItemViewModel>());
            Container.RegisterController<TodoItemController>(TodoItemController);
            Container.RegisterViewModelManager<TodoEditorViewModel>(new ViewModelManager<TodoEditorViewModel>());
            Container.RegisterController<TodoEditorController>(TodoEditorController);
            Container.RegisterViewModelManager<EventMaskViewModel>(new ViewModelManager<EventMaskViewModel>());
            Container.RegisterController<EventMaskController>(EventMaskController);
        }
    }
}
