//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Example {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.IOC;
    using uFrame.Kernel;
    using uFrame.MVVM;
    using uFrame.MVVM.Bindings;
    using uFrame.Serialization;
    using UnityEngine;
    using UniRx;
    using Example;
    
    
    public partial class TodoListViewModelBase : uFrame.MVVM.ViewModel {
        
        private P<String> _TodoContentProperty;
        
        private ModelCollection<TodoItem> _TodoItems;
        
        private Signal<OnBtnAddClickedCommand> _OnBtnAddClicked;
        
        public TodoListViewModelBase(uFrame.Kernel.IEventAggregator aggregator) : 
                base(aggregator) {
        }
        
        public virtual P<String> TodoContentProperty {
            get {
                return _TodoContentProperty;
            }
            set {
                _TodoContentProperty = value;
            }
        }
        
        public virtual String TodoContent {
            get {
                return TodoContentProperty.Value;
            }
            set {
                TodoContentProperty.Value = value;
            }
        }
        
        public virtual ModelCollection<TodoItem> TodoItems {
            get {
                return _TodoItems;
            }
            set {
                _TodoItems = value;
            }
        }
        
        public virtual Signal<OnBtnAddClickedCommand> OnBtnAddClicked {
            get {
                return _OnBtnAddClicked;
            }
            set {
                _OnBtnAddClicked = value;
            }
        }
        
        public override void Bind() {
            base.Bind();
            this.OnBtnAddClicked = new Signal<OnBtnAddClickedCommand>(this);
            _TodoContentProperty = new P<String>(this, "TodoContent");
            _TodoItems = new ModelCollection<TodoItem>(this, "TodoItems");
        }
        
        public virtual void ExecuteOnBtnAddClicked() {
            this.OnBtnAddClicked.OnNext(new OnBtnAddClickedCommand());
        }
        
        public override void Read(ISerializerStream stream) {
            base.Read(stream);
            this.TodoContent = stream.DeserializeString("TodoContent");;
        }
        
        public override void Write(ISerializerStream stream) {
            base.Write(stream);
            stream.SerializeString("TodoContent", this.TodoContent);
        }
        
        protected override void FillCommands(System.Collections.Generic.List<uFrame.MVVM.ViewModelCommandInfo> list) {
            base.FillCommands(list);
            list.Add(new ViewModelCommandInfo("OnBtnAddClicked", OnBtnAddClicked) { ParameterType = typeof(void) });
        }
        
        protected override void FillProperties(System.Collections.Generic.List<uFrame.MVVM.ViewModelPropertyInfo> list) {
            base.FillProperties(list);
            // PropertiesChildItem
            list.Add(new ViewModelPropertyInfo(_TodoContentProperty, false, false, false, false));
            list.Add(new ViewModelPropertyInfo(_TodoItems, false, true, false, false));
        }
    }
    
    public partial class TodoListViewModel {
        
        public TodoListViewModel(uFrame.Kernel.IEventAggregator aggregator) : 
                base(aggregator) {
        }
    }
}
