//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Example {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.Kernel;
    using uFrame.MVVM;
    using uFrame.MVVM.Bindings;
    using uFrame.Serialization;
    using Example;
    
    
    public class TodoItemsContentViewBase : uFrame.MVVM.ViewComponent {
        
        public virtual TodoListViewModel TodoList {
            get {
                return (TodoListViewModel)this.View.ViewModelObject;
            }
        }
        
        public virtual void ExecuteOnBtnAddClicked() {
            TodoList.OnBtnAddClicked.OnNext(new OnBtnAddClickedCommand() { Sender = TodoList });
        }
        
        public virtual void ExecuteBtnShowFinishedListCllicked() {
            TodoList.BtnShowFinishedListCllicked.OnNext(new BtnShowFinishedListCllickedCommand() { Sender = TodoList });
        }
        
        public virtual void ExecuteBtnShowTodoListClicked() {
            TodoList.BtnShowTodoListClicked.OnNext(new BtnShowTodoListClickedCommand() { Sender = TodoList });
        }
        
        public virtual void ExecuteOnBtnAddClicked(OnBtnAddClickedCommand command) {
            command.Sender = TodoList;
            TodoList.OnBtnAddClicked.OnNext(command);
        }
        
        public virtual void ExecuteBtnShowFinishedListCllicked(BtnShowFinishedListCllickedCommand command) {
            command.Sender = TodoList;
            TodoList.BtnShowFinishedListCllicked.OnNext(command);
        }
        
        public virtual void ExecuteBtnShowTodoListClicked(BtnShowTodoListClickedCommand command) {
            command.Sender = TodoList;
            TodoList.BtnShowTodoListClicked.OnNext(command);
        }
    }
    
    public class TodoItemViewComponentBase : uFrame.MVVM.ViewComponent {
        
        public virtual TodoListViewModel TodoList {
            get {
                return (TodoListViewModel)this.View.ViewModelObject;
            }
        }
        
        public virtual void ExecuteOnBtnAddClicked() {
            TodoList.OnBtnAddClicked.OnNext(new OnBtnAddClickedCommand() { Sender = TodoList });
        }
        
        public virtual void ExecuteBtnShowFinishedListCllicked() {
            TodoList.BtnShowFinishedListCllicked.OnNext(new BtnShowFinishedListCllickedCommand() { Sender = TodoList });
        }
        
        public virtual void ExecuteBtnShowTodoListClicked() {
            TodoList.BtnShowTodoListClicked.OnNext(new BtnShowTodoListClickedCommand() { Sender = TodoList });
        }
        
        public virtual void ExecuteOnBtnAddClicked(OnBtnAddClickedCommand command) {
            command.Sender = TodoList;
            TodoList.OnBtnAddClicked.OnNext(command);
        }
        
        public virtual void ExecuteBtnShowFinishedListCllicked(BtnShowFinishedListCllickedCommand command) {
            command.Sender = TodoList;
            TodoList.BtnShowFinishedListCllicked.OnNext(command);
        }
        
        public virtual void ExecuteBtnShowTodoListClicked(BtnShowTodoListClickedCommand command) {
            command.Sender = TodoList;
            TodoList.BtnShowTodoListClicked.OnNext(command);
        }
    }
}
